config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'flowers#index'
  resources :flowers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flower.rb
class Flower < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  def index
    @flowers = Flower.all
  end

  def show
    @flower = Flower.find(params[:id])
  end

  def new
    @flower = Flower.new
  end

  def create
    @flower = Flower.new(params.require(:flower).permit(:name, :price))
    if @flower.save
      flash[:notice] = 'Flower Added'
      redirect_to @flower
    else
      render :new
    end
  end

  def edit
    @flower = Flower.find(params[:id])
  end

  def update
    @flower = Flower.find(params[:id])
    if @flower.update(params.require(:flower).permit(:name, :price))
      flash[:notice] = 'Flower Updated'
      redirect_to @flower
    else
      render :edit
    end
  end

  def destroy
    @flower = Flower.find(params[:id])
    @flower.destroy
    redirect_to flowers_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/views/flowers/_form.html.erb
<%= form_with model: flower do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% flower.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %><br>
    <% flower.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
    <%= link_to 'Back', flowers_path, class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/flowers/edit.html.erb
<h2>New Flower</h2>
<%= render 'form', flower: @flower %>
<br>

<div>
  <%= link_to 'View', @flower%>
</div>

app/views/flowers/index.html.erb
<h2>Available Flowers</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Actions</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @flowers.each do |flower| %>
      <tr>
        <td><%= flower.name %></td>
        <td><%= flower.price %></td>
        <td><%= link_to 'Show', flower_path(flower) %></td>
        <td><%= link_to "Edit", edit_flower_path(flower) %></td>
        <td><%= button_to "Remove", flower, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
  <%= link_to 'Add flower', new_flower_path %>
</p>

app/views/flowers/new.html.erb
<h2>New Flower</h2>
<%= render 'form', flower: @flower %>

app/views/flowers/show.html.erb
<h1><%= @flower.name %></h1>

<p><%= @flower.price %></p>
<br>
<div>
<%= link_to "Edit", edit_flower_path(@flower) %>
<%= button_to "Destroy", @flower, method: :delete %>
<%= link_to 'Back', root_path%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowerGallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>